name: Run Playwright Tests on 3 Browsers

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        playwright install

    - name: Run tests on ${{ matrix.browser }}
      run: |
        source venv/bin/activate
        BROWSER=${{ matrix.browser }} behave -f allure_behave.formatter:AllureFormatter -o allure_results_${{ matrix.browser }}

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure_results_${{ matrix.browser }}
        path: allure_results_${{ matrix.browser }}

  merge-reports:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Merge Allure Results
      run: |
        mkdir merged_results
        find artifacts -type d -name "allure_results_*" -exec cp -r {}/* merged_results/ \;

    - name: Generate Allure Report
      run: |
        npm install -g allure-commandline
        allure generate merged_results -o allure-report --clean

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report