name: Run Playwright Tests on 3 Browsers

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies for Playwright
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-0 \
          libgtk-4-1 \
          libxss1 \
          libnss3 \
          libx11-xcb1 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          libgbm1 \
          libpango-1.0-0 \
          libcairo2 \
          libatspi2.0-0 \
          libdrm2 \
          libwoff1 \
          libvpx9 \
          libevent-2.1-7 \
          libopus0 \
          libavif16 \
          libsecret-1-0 \
          libharfbuzz-icu0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libgstreamer-gl1.0-0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-libav \
          flite \
          libgles2 \
          libasound2t64 \
          libwoff2dec0


    - name: Set up Python & install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        playwright install

    - name: Run tests on ${{ matrix.browser }}
      run: |
        source venv/bin/activate
        BROWSER=${{ matrix.browser }} behave -f allure_behave.formatter:AllureFormatter -o allure_results_${{ matrix.browser }}

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure_results_${{ matrix.browser }}
        path: allure_results_${{ matrix.browser }}

  merge-reports:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Merge Allure Results
      run: |
        mkdir merged_results
        find artifacts -type d -name "allure_results_*" -exec cp -r {}/* merged_results/ \;

    - name: Generate Allure Report
      run: |
        npm install -g allure-commandline
        allure generate merged_results -o allure-report --clean

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report